name: mcp-drug-discovery
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  # Python and core dependencies
  - python=3.11
  - pip
  
  # Core scientific computing
  - numpy>=1.24.0
  - pandas>=2.1.0
  - scipy>=1.11.0
  - scikit-learn>=1.3.0
  
  # Web framework and API
  - fastapi>=0.104.0
  - uvicorn>=0.24.0
  - httpx>=0.25.0
  
  # Data validation and configuration
  - pydantic>=2.5.0
  - pydantic-settings>=2.1.0
  - pyyaml>=6.0
  
  # CLI and utilities
  - typer>=0.9.0
  - tqdm>=4.66.0
  - loguru>=0.7.0
  
  # Network and graph analysis
  - networkx>=3.2.0
  - requests>=2.31.0
  
  # File handling
  - aiofiles>=23.2.0
  - openpyxl>=3.1.0
  
  # Visualization
  - plotly>=5.17.0
  - matplotlib>=3.7.0
  - seaborn>=0.12.0
  
  # Bioinformatics
  - biopython>=1.82
  - rdkit>=2023.9.0
  
  # Caching and async
  - redis-py>=5.0.0
  
  # Development tools
  - pytest>=7.4.0
  - pytest-asyncio>=0.21.0
  - pytest-cov>=4.1.0
  - black>=23.11.0
  - isort>=5.12.0
  - flake8>=6.1.0
  - mypy>=1.7.0
  - pre-commit>=3.6.0
  
  # Jupyter for interactive development
  - jupyter>=1.0.0
  - ipykernel>=6.25.0
  - notebook>=7.0.0
  
  # System dependencies for molecular modeling
  - openbabel>=3.1.0
  
  # Additional bioinformatics tools (optional)
  # - blast>=2.14.0
  # - hmmer>=3.3.0
  
  # Pip dependencies (for packages not available in conda)
  - pip:
    - rdkit-pypi>=2023.3.0
    # - pymol-open-source>=2.5.0  # Optional
    # - deepchem>=2.7.0  # Optional
    # - torch>=2.0.0  # Optional
    # - transformers>=4.35.0  # Optional
    # - huggingface-hub>=0.17.0  # Optional
