chembl:
  min_pchembl: 6.0
  min_comparators: 5
  require_assay_consistency: true

similarity:
  top_k: 50
  min_cosine_geminimol: 0.60
  min_tanimoto_morgan: 0.40

pharmacophore:
  method: "disabled"  # Disable pharmacophore for simple test

scoring:
  weights:
    similarity: 0.50
    qsar: 0.00
    pharmacophore: 0.00
    docking: 0.00
    evidence: 0.50

ligand_prep:
  input_paths:
    - "data/compounds/pyrazole_conjugates/*.mol"
  ph: 7.4
  strip_salts: true
  largest_fragment_only: true
  enumerate:
    enable: false
  conformers:
    enable: false  # Disable 3D conformers for speed
  export:
    formats: ["smi"]

output:
  dir: "data/outputs"
  save_neighbors_topk: 25

docking:
  enabled: false

# Simple test with mock data
test_mode: true
mock_evidence: 0.8

disease_terms: ["lung cancer"]
organism: "Homo sapiens"
