# Test configuration for pyrazole conjugates against general cancer
# Using the enhanced non-docking pipeline with E3FP, GeminiMol, and Ouroboros

disease_terms: ["cancer", "neoplasms", "tumor"]
organism: "Homo sapiens"

# Pyrazole conjugates compounds
ligand_prep:
  input_paths:
    - "data/compounds/pyrazole_conjugates/*.mol"
  ph: 7.4
  strip_salts: true
  largest_fragment_only: true
  enumerate:
    enable: false
    max_tautomers: 6
    max_stereoisomers: 2

# Target discovery settings
max_targets: 30
ppi:
  min_confidence: 0.4
  max_interactions: 1500

expression:
  min_tissue_expression: 0.1
  required_tissues: ["liver", "lung", "breast", "colon", "prostate"]

structures:
  require_structure: false
  min_resolution: 3.0

# Enhanced similarity settings
similarity:
  top_k: 50
  min_tanimoto_morgan: 0.25
  enable_e3fp: true  # Enable E3FP 3D fingerprints
  e3fp:
    radius: 2
    shells: 5
    top_k: 25

# GeminiMol integration
representations:
  geminimol:
    enabled: true
    repo_path: third_party/GeminiMol
    model_path: third_party/GeminiMol/models/GeminiMol
    use_pharm_profiler: true

# Ouroboros integration (optional)
ouroboros:
  enabled: false  # Disable for initial testing
  repo_path: third_party/Ouroboros
  model_name: "Ouroboros_M1c"
  jobs: []

# Pharmacophore settings
pharmacophore:
  method: "rdkit_features"
  min_ph4_support: 0.40

# ChEMBL evidence settings
chembl:
  min_pchembl: 6.0
  min_comparators: 5
  require_assay_consistency: true

# Enhanced scoring weights
scoring:
  weights:
    morgan_2d: 0.30
    e3fp: 0.10
    geminimol: 0.25
    pharmacophore: 0.25
    evidence: 0.10

# Output settings
output_dir: "data/outputs"
debug_mode: true
cache_results: true

# Visualization
visualization:
  enabled: true
  title: "Pyrazole Conjugates vs Cancer Targets"


