chembl:
  min_pchembl: 6.0
  min_comparators: 3
  require_assay_consistency: true
  use_real_data: true  # Enable real ChEMBL data

similarity:
  top_k: 50
  min_cosine_geminimol: 0.60
  min_tanimoto_morgan: 0.40

pharmacophore:
  method: "rdkit_features"
  min_ph4_support: 0.60

scoring:
  weights:
    similarity: 0.40
    qsar: 0.00
    pharmacophore: 0.20
    docking: 0.00  # No docking
    evidence: 0.40

ligand_prep:
  input_paths:
    - "data/compounds/pyrazole_conjugates/*.mol"
  ph: 7.4
  strip_salts: true
  largest_fragment_only: true
  enumerate:
    enable: false
    max_tautomers: 6
    max_stereoisomers: 2
    allow_chiral_perms: false
  conformers:
    enable: false  # Disable 3D conformers to speed up test
    max_confs: 10
    prune_rms: 0.5
    forcefield: "MMFF94"
    max_iter: 200
  export:
    formats: ["smi", "sdf"]

output:
  dir: "data/outputs"
  save_neighbors_topk: 25

docking:
  enabled: false  # No docking as requested

# Test targets for lung cancer
test_targets:
  - chembl_id: "CHEMBL201"
    uniprot_id: "P00533"
    gene_name: "EGFR"
  - chembl_id: "CHEMBL203"
    uniprot_id: "P04626"
    gene_name: "ERBB2"
  - chembl_id: "CHEMBL197"
    uniprot_id: "P11362"
    gene_name: "FGFR1"

disease_terms: ["lung cancer", "non-small cell lung cancer", "NSCLC", "pulmonary carcinoma"]
organism: "Homo sapiens"
