chembl:
  min_pchembl: 4.0  # Lower threshold to get more data
  min_comparators: 3
  require_assay_consistency: true

similarity:
  top_k: 50
  min_cosine_geminimol: 0.60
  min_tanimoto_morgan: 0.40

pharmacophore:
  method: "rdkit_features"
  min_ph4_support: 0.60

scoring:
  weights:
    similarity: 0.40
    qsar: 0.00
    pharmacophore: 0.20
    docking: 0.00
    evidence: 0.40

ligand_prep:
  input_paths:
    - "data/compounds/pyrazole_conjugates/*.mol"
  ph: 7.4
  strip_salts: true
  largest_fragment_only: true
  enumerate:
    enable: false
    max_tautomers: 6
    max_stereoisomers: 2
    allow_chiral_perms: false
  conformers:
    enable: false
    max_confs: 10
    prune_rms: 0.5
    forcefield: "MMFF94"
    max_iter: 200
  export:
    formats: ["smi", "sdf"]

output:
  dir: "data/outputs"
  save_neighbors_topk: 25

docking:
  enabled: false

# Use targets that actually have data in ChEMBL
test_targets:
  - chembl_id: "CHEMBL2095173"  # Potassium-transporting ATPase (has IC50 data)
    uniprot_id: "P20648"
    gene_name: "ATP4A"
  - chembl_id: "CHEMBL25"  # Aspirin target (has data)
    uniprot_id: "P23219"
    gene_name: "PTGS1"

disease_terms: ["lung cancer"]
organism: "Homo sapiens"

visualization:
  enabled: true
  title: "Real ChEMBL Data Analysis"
