chembl:
  min_pchembl: 6.0
  min_comparators: 5
  require_assay_consistency: true
  limit: 200                 # cap activities per target to improve latency

similarity:
  top_k: 50
  min_tanimoto_morgan: 0.25    # relaxed for discovery runs
  enable_e3fp: false           # new; default off until E3FP is installed
  e3fp:
    radius: 2
    shells: 5
    top_k: 25

representations:
  geminimol:
    enabled: true
    repo_path: third_party/GeminiMol
    model_path: third_party/GeminiMol/models/GeminiMol   # per README
    use_pharm_profiler: true

ouroboros:
  enabled: true                      # generation/analysis is optional
  repo_path: third_party/Ouroboros
  model_name: "Ouroboros_M1c"        # example name per authors; change as needed
  jobs: []                           # list of job dicts; see below

pharmacophore:
  method: "rdkit_features"  # set to "disabled" to turn off
  min_ph4_support: 0.40     # relaxed for discovery runs

scoring:
  weights:
    morgan_2d: 0.30
    e3fp: 0.10
    geminimol: 0.25
    pharmacophore: 0.25
    evidence: 0.10

ligand_prep:
  input_paths:
    - "data/compounds/*.smi"
    - "data/compounds/*.sdf"
  ph: 7.4
  strip_salts: true
  largest_fragment_only: true
  enumerate:
    enable: false
    max_tautomers: 6
    max_stereoisomers: 2
    allow_chiral_perms: false
  conformers:
    enable: true
    max_confs: 10
    prune_rms: 0.5
    forcefield: "MMFF94"
    max_iter: 200
  export:
    formats: ["smi", "sdf"]

output:
  dir: "data/outputs"
  save_neighbors_topk: 25

docking:
  enabled: false
  method: "vina"
  pocket_source: "cocrystal"   # "fpocket" | "p2rank" later if you enable
  margin_angstrom: 12.0
  exhaustiveness: 16
  num_modes: 9
  receptor_pdb_path: ""   # optional: path to PDB/mmCIF for docking when pocket is validated
  cocrystal:
    ligand_resname: ""     # required to define pocket from co-crystal ligand
    chain_id: ""           # optional; used if SIFTS mapping is enforced
    uniprot_id: ""         # optional; used if SIFTS mapping is enforced
  auto_validate: false       # if true and pdb_id provided, try BioLiP+SIFTS validation
  pdb_id: ""                # optional PDB ID used for BioLiP/SIFTS validation

visualization:
  enabled: true
  output_dir: "data/outputs/visualizations"
  title: "OmniTarget MCP Report"
  dashboard:
    enabled: false
    port: 8050
    host: "127.0.0.1"
  plots:
    formats: ["png", "svg"]
    dpi: 200
    style: "seaborn"
  reports:
    formats: ["html"]
    template: "executive"
    include_molecular: false
  molecular:
    viewer: "rdkit"
    show_pharmacophore: true
    show_docking: false

disease_terms: ["example"]  # used for discovery; leave as placeholder term
organism: "Homo sapiens"
